import * as Yup from "yup";

export const INTIAL_VALUES = {
  owner: "",
  property: "",
  improvements: "",
  home: "",
  addtion: "",
  newGarage: "",
  setbacks: "",
  sides: "",
  rear: "",
  outBuilding: "",
  colon: "",
  material: "",
  roof: "",
  signatureOwner: "",
  email: "",
  printedName: "",
  cellPhone: "",
  altPhone: "",
  mailingAddress: "",
  city: "",
  state: "",
  zip: "",
  architectDesigner: "",
  copmanyName: "",
  officePhone: "",
  contractor: "",
};

export const VALIDATION_SCHEMA = Yup.object({
  owner: Yup.string().required("Please provide your name"),
  property: Yup.string().required("Please provide property"),
  improvements: Yup.string().required("Please enter   improvements"),
  home: Yup.string().required("Please enter Home"),
  addtion: Yup.string().required("Please enter Addition"),
  newGarage: Yup.string().required("Please provide new Garage info"),
  setbacks: Yup.string().required("Please Enter set backs"),
  sides: Yup.string().required("Please provide sides info"),
  rear: Yup.string().required("Please provide rear info"),
  outbuilding: Yup.string().required("Please Enter Your out building info"),
  colon: Yup.string().required("Please provide data"),
  material: Yup.string().required("Please provide your Material info"),
  roof: Yup.string().required("Please Enter roof info"),
  question: Yup.string().required("Please fill this question"),

  signatureOwner: Yup.string().required("Please provide your signature"),
  email: Yup.string().required("Please provide email"),
  printedName: Yup.string().required("Please enter printed name"),
  cellPhone: Yup.string().required("Please enter cell phone"),
  altPhone: Yup.string().required("Please enter alternate phone"),
  mailingAddress: Yup.string().required("Please provide mailing info"),
  city: Yup.string().required("Please Enter set city"),
  state: Yup.string().required("Please provide state"),
  zip: Yup.string().required("Please provide rear zip"),
  architectDesigner: Yup.string().required(
    "Please Enter Your architect/designer name"
  ),
  copmanyName: Yup.string().required("Please provide copmany name"),
  officePhone: Yup.string().required("Please provide office phone"),
  contractor: Yup.string().required("Please provide contractor Name"),
});
